- sat-practice-app/package-lock.json
- sat-practice-app/package.json
- sat-practice-app/scripts/importOptionsFromJson.mjs
- sat-practice-app/scripts/importQuestionsFromJson.mjs
- sat-practice-app/src/app/components/ChatSidebar.jsx
- sat-practice-app/src/app/components/ProgressBar.jsx
- sat-practice-app/src/app/components/Question.jsx
- sat-practice-app/src/app/components/QuestionStatus.jsx
- sat-practice-app/src/app/components/topics.jsx
- sat-practice-app/src/app/home/page.jsx
- sat-practice-app/src/app/skills/components/SkillCard.jsx
- sat-practice-app/src/app/skills/page.jsx
- sat-practice-app/src/components/Sidebar.tsx
Skills Section updated to reflect correct subcategories and distributions. 
Front end Change for Ai chat.
Simple UI changes throughout
Created scripts to upload newly filtered questions and options to DB
> changes to how front end interacts with database

- sat-practice-app/src/app/components/Question.jsx
- sat-practice-app/src/app/skills/components/DomainSection.jsx
- sat-practice-app/src/app/skills/page.jsx
Changes Made
- Modified the `renderResponse` function to normalize underscores
- Added regex to replace 6 or more consecutive underscores with exactly 5 underscores
- Improved question text rendering for better readability
Standardized some colors and layout across pages
> Formatting and Ui changes

- sat-practice-app/src/app/TestMode/page.jsx
- sat-practice-app/src/app/TestMode/test.css
> Add timer warning and enhanced time display in test mode

- sat-practice-app/public/landing/index.html
> landing page

- sat-practice-app/public/landing/index.html
Added Founding team section and faq section finalized. Call to action section and footer minimized
> landing page finalized

- sat-practice-app/src/app/PracticeTestMode/page.jsx
- **logo in footer**
- **updated phone number link**
- **question number prints once in question component**
- **analytics card component and progress page stats match**
- **my changes before merging upstream**
- **logo in footer**
- **forgot password feature**
- **demo updates**
- **replace video**
- **timer resumes when you nav back to practice test from another tab**
- **pausing fixed if you nav to other pages**
> fixed practice test pausing problems

- sat-practice-app/src/app/progress/page.jsx
- **logo in footer**
- **updated phone number link**
- **question number prints once in question component**
- **analytics card component and progress page stats match**
- **my changes before merging upstream**
- **logo in footer**
- **forgot password feature**
- **demo updates**
- **replace video**
- **timer resumes when you nav back to practice test from another tab**
- **pausing fixed if you nav to other pages**
- **fixed mark for review button**
- **styling changes**
- **VIDEOS AGAIN**
- **removed filler data**
> removed filler data

- README.md
- sat-practice-app/public/index.html
- **logo in footer**
- **updated phone number link**
- **question number prints once in question component**
- **analytics card component and progress page stats match**
- **my changes before merging upstream**
- **logo in footer**
- **forgot password feature**
- **demo updates**
- **replace video**
- **timer resumes when you nav back to practice test from another tab**
- **pausing fixed if you nav to other pages**
- **fixed mark for review button**
- **styling changes**
- **VIDEOS AGAIN**
- **removed filler data**
- **Create README.md**
- **reset password functionalities**
- **landing problem**
- **f'**
- **f**
- **f**
- **f**
- **f**
- **s**
> added readme

- sat-practice-app/src/components/Sidebar.tsx
- sat-practice-app/src/components/sidebar.module.css
> Sidebar toggle to open and close instead of hover

- sat-practice-app/src/app/layout.js
- sat-practice-app/src/components/ConditionalLayout.tsx
> Do not show sidebar on /login, /signup, /forgot-password, or /pricing

- sat-practice-app/src/app/components/ChatSidebar.jsx
as descibred^
screenshot shows manual llm cancellation request button
> feature: cancel llm request, cancels when question changes as well

- sat-practice-app/src/app/api/chat/route.js
- sat-practice-app/src/app/components/ChatSidebar.jsx
- sat-practice-app/src/app/hooks/useChat.js
llm responses are now persisted in memory so users can chat back and forth with the model
> llm responses are now persisted in memory and UI

- sat-practice-app/src/app/PracticeTestMode/page.jsx
- sat-practice-app/src/app/components/DesmosGraph.jsx
Math test page now has desmos integration
> desmos calculator added

- sat-practice-app/src/app/api/user-stats/route.js
> home page analytics card time frame changed to unbounded

- sat-practice-app/src/app/home/page.jsx
- sat-practice-app/src/app/progress/page.jsx
- sat-practice-app/src/components/SubscriptionCheck.tsx
no more 'verifying subscription...' with no spinner
replaced all loading states with one general state for a cleaner look
> loading state visual improvements

- sat-practice-app/src/app/TimedTestDash/page.jsx
- sat-practice-app/src/app/components/AIChatGeneral.jsx
- sat-practice-app/src/app/components/AnalyticsCard.jsx
- sat-practice-app/src/app/components/DifficultyModal.jsx
- sat-practice-app/src/app/components/Question.jsx
- sat-practice-app/src/app/components/SubjectSection.jsx
- sat-practice-app/src/app/components/TimedPractice.jsx
- sat-practice-app/src/app/components/topics.jsx
- sat-practice-app/src/app/skills/components/SkillCard.jsx
- sat-practice-app/src/app/subscription/page.jsx
eg. (card hovers and button changes color)
> button animations

- sat-practice-app/src/app/components/ChatSidebar.jsx
> spacing and formatting of llm resopnse

- sat-practice-app/src/app/api/chat/route.js
- sat-practice-app/src/app/hooks/useChat.js
llm was cutting responses short, now its fixed
> llm cutoff fixed

- sat-practice-app/src/app/components/DifficultyModal.jsx
- sat-practice-app/src/app/components/ProgressBar.jsx
- sat-practice-app/src/app/components/Question.jsx
- sat-practice-app/src/app/practice/page.jsx
> added submit early and dynamic question amounts

- sat-practice-app/src/app/api/skill-questions/route.js
- sat-practice-app/src/app/components/DifficultyModal.jsx
skills section previously would not show the selected question amount
> fixed skills bug
